# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nguyen Hong Phuc
title: Intern Web Developer
email: hongphuc71233@gmail.com
# email_title: Email (Email title override)
phone: 0342118130
# phone_title: Phone (Phone title override)
website: https://github.com/Hong-Phuc
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: Hong-Phuc
dribbble_username: ReFelix7
linkedin_username: Hong Phuc Nguyen


about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I am a passionate web developer with a strong foundation in **HTML, CSS, JavaScript, PHP, and Python**.  
  My primary focus is on **building dynamic and responsive web applications**, and I am currently expanding my expertise in **React.js** and **Android development**.  

  While I have experience working with databases like **MongoDB and MySQL**, I primarily focus on integrating them into web applications rather than deep database optimization.  

  I am always eager to learn new technologies and enhance my skills in both **frontend and backend development**.  
  Looking forward to contributing and growing in a professional IT environment.

content:
  - title: Projects  
    layout: list  
    content:
      - layout: left
        border: weak  
        title: Shoe Store Website  
        link: https://github.com/Bug03/doanweb2  
        link_text: View on GitHub  
        additional_links:
          - title: GitHub Repository  
            icon: fab fa-github  
            url: https://github.com/Bug03/doanweb2
        quote: >  
          A dynamic e-commerce website for selling shoes, built as a university project.  
        description: |  
          Developed a **shoe store website** using **PHP, JavaScript, and MySQL**, implementing key e-commerce features such as product browsing, shopping cart, and order management.  
          - Designed a **responsive UI** with HTML, CSS, and JavaScript.  
          - Implemented **AJAX for seamless user interactions** such as filtering products and updating the cart without reloading the page.  
          - Managed user authentication and product data with **PHP and MySQL**.  

  - title: Experience  
    layout: list  
    content:  
      - layout: right  
        title: "Personal Projects"  
        sub_title: "Web Developer"  
        caption: "2021 - Present"  
        link: ""  
        quote: >  
          Worked on various web projects, focusing on frontend and backend development.  
        description: |  
          - Developed multiple responsive websites using **HTML, CSS, SASS, and JavaScript**.  
          - Built dynamic web applications using **PHP and Python (Flask/Django)**.  
          - Integrated APIs and databases (MySQL, MongoDB) to enhance web functionalities.  
          - Implemented performance optimizations to improve page loading speed.  
        
 



  - title: Education  
    layout: list  
    content:  
      - layout: top-right  
        title: Sai Gon University  
        sub_title: Bachelor's in Information Technology  
        caption: 2021 - 2026  
        quote: >  
          Focused on web development, software engineering, and database management.  
        description: |  
          - Built multiple web projects using **PHP, JavaScript, and MySQL**.  
          - Gained experience in **React.js and Android development** through coursework and self-learning.  

  - title: A Little More About Me  
    layout: text  
    content: |  
      Apart from coding, I enjoy **learning and experimenting with new web technologies**.  
      I often spend time **watching tech-related videos, reading blogs**, and trying out new frameworks like **React.js** and **Android development**.  

      I am also interested in **improving code quality and optimizing performance**, always looking for ways to write cleaner and more efficient code.  
      Besides technology, I enjoy **listening to music, watching movies**, and sometimes playing sports to stay active. 🚀  


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
